### ISSUE TITLE
error on Advanced example

### ISSUE THREAD

**Issue by vip3r011** [sethblack/javascript-fortuna#5]
hi when i try to run the advanced example with node 8.10.0

i get the following error: 

"jsspg.initialized = true;
^

ReferenceError: jsspg is not defined
    at Object.<anonymous> (/root/indextest.js:28:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3"

[indextest.zip](https://github.com/sethblack/javascript-fortuna/files/2000484/indextest.zip)

any ideas?

**Comment by vip3r011** [comment]
working: i forgot to install npm i javascript-strong-password-generator
 and had to modify exmaple a bit:
[https://pastebin.com/fipu6fW5](url)

**Comment by sethblack** [comment]
Ahhh! Ok. Yeah I should definitely be more explicit about that. Sorry for the confusion. #baddocumentation

**Comment by sethblack** [comment]
Fixed! :D
